config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'boards#index'

  resources :boards do
    resources :posts, except: [:index], shallow: true do
      resources :comments, shallow: true do
        post :vote
        get :score
      end
    end
  end

  resources :moderators, except: [:show, :edit, :update]
  get "/sandbox/counter" => "sandbox#counter"
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :users
  has_many :posts
  has_many :comments, through: :posts

  validates_presence_of :topic
  validates_length_of :topic, minimum: 2
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # before_action except: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def new
    @board = Board.new
    authorize @board
  end

  def index
    @boards = Board.all
  end

  def create
    @board = Board.new(topic: params[:board][:topic])
    authorize @board
    if @board.save
      flash[:notice] = "Board created!"
      redirect_to @board
    else
      render :new
    end
  end

  def show
    @board = Board.find params[:id]
    authorize @board
  end

  def destroy
    board = current_user.boards.find params[:id]
    authorize board
    board.destroy
    redirect_to "/boards"
  end

  private

  # def set_board
  #   @board = Board.find(params[:board_id])
  # end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<h2>Welcome to RoR Boards!</h2>

<%= link_to "Start A New Board", new_board_path, class: "btn btn-default" %>

<h2><font color="purple">Existing RoR Boards:</font></h2>
<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Topic</th>
      <th>Posts</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to board.topic, board_path(board) %></td>
        <%# <td><%= board.topic%></td> %>
        <td><%= board.posts.count %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h1>Start a New Board</h1>

 <%= bootstrap_form_for @board, url: boards_path do |f| %>
     <%= f.text_field :topic%>
       <button class="btn btn-primary">Create</button>
     <% end %>

app/views/boards/show.html.erb
<h3><%= @board.topic%></h3>

<h4>Posts: <span class="badge"><%= @board.posts.count %></span></h4>

<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Post Title</th>
      <th>Author</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @board.posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(@board) %></td>
        <td><%= User.find(post.user_id).email %></td>
        <td><span class="badge"><%= post.comments.count %></span></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Post Here", new_board_post_path(@board), class: "btn btn-default" %>