config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'boards#index'

  resources :boards do
    resources :posts, except: [:index], shallow: true do
      resources :comments, shallow: true do
        post :vote
        get :score
      end
    end
  end

  resources :moderators, except: [:show, :edit, :update]
  get "/sandbox/counter" => "sandbox#counter"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :board
  belongs_to :user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_board, except: [:destroy, :new, :edit, :update, :show] 
  def index
    @posts = Post.all
  end

  def new
    @board = Board.find(params[:board_id])
    @post = @board.posts.new user_id: current_user.id
    authorize @post
  end

  def create
    @board = Board.find(params[:board_id])
    @post = @board.posts.new post_params
    authorize @post
    if @post.save
      flash[:notice] = "Posted!"
      redirect_to @board
    else
      render :new
    end
  end

  def edit
    @post = Message.find(params[:id])
    @board = @post.board
    authorize @post
  end

  def update
    @post = Message.find(params[:id])
    authorize @post
    if @post.update post_params
      flash[:notice] = "Post updated!"
      redirect_to @post.board
    else
      render :edit
    end
  end

  def destroy
    @post = Message.find(params[:id])
    authorize @post
    if @post.delete
      flash[:notice] = "Post deleted!"
      redirect_to @post.board
    else
      render "board/show"
    end
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
  end
  
  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content,:user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/new.html.erb
<h1>Make a Post</h1>

<%= bootstrap_form_for @post, url: board_posts_path do |f| %>
  <%= f.text_field :title%>
  <%= f.text_field :content%>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <%= f.hidden_field :board_id, value: @board.id%>
  <button class="btn btn-primary">Post</button>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title%></h2>


<h3><%= @post.content%></h3>


<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th><h4>Comments: <span class="badge"><%= @post.comments.count %></span></h4></th>
      <th>Score</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <%#       <%= link_to comment_vote_path(comment, value: 1), method: :post do %1> %> 
        <%#         <span class="glyphicon glyphicon-upload up-btn"></span> %>
        <%#       <%end%>
      <%#       <%= link_to comment_vote_path(comment, value: -1), method: :post do %1> %> 
      <%#         <span class="glyphicon glyphicon-download"></span> %>
      <%#       <%end%> 
    <td>
      <a href="#" class="glyphicon glyphicon-upload up-btn" data-comment-id = <%= comment.id %>>
      <a href="#" class="glyphicon glyphicon-download down-btn" data-comment-id = <%= comment.id %>>
    </td>
    <%# <td><%= Vote.where(comment_id: comment.id).pluck(:value).flatten.reduce(:+) %1></td> %>
        <td class="total-votes" data-comment-id = <%= comment.id %>></td>
      <td><%= User.find(comment.user_id).email %></td>
  </tr>
<% end %>
  </tbody>
</table>

<h4>Make a comment</h4>
<%= link_to "Comment", new_post_comment_path(@post),class: "btn btn-default"%>